---
title: "HBN Final Sample Selection"
author: "Audrey Luo"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dplyr)
library(purrr)
library(stringr)
library(tidyr)
```

# Initial Participant List
```{r}
#list of RBC ids with processed, non-variant diffusion MRI data, T1, and fieldmaps: N = 2063
participants <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_NonVariantDWI_participantlist.csv") # generated by /cbica/projects/luo_wm_dev/two_axes_manuscript/code/sample_construction/identify_variants/identify_variants.py
colnames(participants) <- c("sub") 

# exclude participants not in pod2 data
# tsv from https://fcp-indi.s3.amazonaws.com/index.html#data/Projects/HBN/BIDS_curated/derivatives/qsiprep/)
# exclude participants that had didn't have preprocessed, BIDS-compliant dMRI data (based on HBN-POD2 curation)
pod2 <- read.delim("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN-POD2.tsv")
pod2 <- pod2 %>% rename(sub=subject_id)
participants.final <- inner_join(participants, pod2[,c('sub', 'expert_qc_score', 'xgb_qsiprep_qc_score', 'xgb_qc_score', 'dl_qc_score', 'site_variant')], by = "sub")  # remove 24 participants from sample of 2063 due to not being BIDS-compliant dMRI data, remaining N = 2039 

# exclude if had ACBD sequence
pod2exclude_abcd <- participants.final %>% filter(str_detect(site_variant, "ABCD"))
participants.final <- participants.final[!participants.final$sub %in% pod2exclude_abcd$sub,] %>% as.data.frame() # remove 15 participants from sample of 2039 due to ABCD sequence, remaining N = 2024

# exclude staten island (1.5 T)
dwi.qc <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/diffusion_qcmetrics.ipynb
dwi.qc <- dwi.qc %>% rename(sub=subject_id) %>% rename(site=session_id) # format site variable
dwi.qc$site <- gsub("ses-", "", dwi.qc$site)
staten_island <- dwi.qc$sub[which(dwi.qc$site=="HBNsiteSI")]
participants.final <- participants.final[!participants.final$sub %in% staten_island,] %>% as.data.frame() # remove 269 participants from sample of 2024 for having 1.5T data, remaining N = 1755

# Actual starting N = 1755 (3T non-variant diffusion MRI data, T1, and fieldmaps)
```

# Construct Final Sample
```{r}
demographics <- read.delim("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_Demographics.tsv") # copied over from network_replication
demographics <- demographics %>% rename(sub=participant_id)
demographics <- demographics[demographics$sub %in% participants.final$sub,] #demographic, medical, and clinical information for just the N = 1755 participants with non-variant diffusion MRI data
```

## Health History Exclusion
```{r}
#no additional medical exclusion in HBN
```

## T1 Quality Exclusion
```{r}
# participants to exclude based on manual QA: exclude T1 based on `tri.nary_score_without_rater.2`==0
# note that trinary score == 2 means good, == 0 means bad, == 1 means in between
T1_QA <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/T1_QA_HBN_NathaliaEsper_20230630.csv")
T1_QA <- T1_QA %>% rename(sub=ID)
T1_QA <- T1_QA %>% mutate(t1Exclude = ifelse(tri.nary_score_without_rater.2 == 0, 1, 0))
T1_qualityexclude <- T1_QA %>% filter(t1Exclude==1) %>% select(sub)

participants.final <- participants.final[!participants.final$sub %in% T1_qualityexclude$sub,] %>% as.data.frame() #remove 72 participants from the sample of 1755, remaining N = 1683
```

## Diffusion Acquisition Exclusion
```{r}
dwi.qc <- read.csv("/cbica/projects/luo_wm_dev/input/HBN/sample_selection_files/HBN_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by /cbica/projects/luo_wm_dev/code/Generate_input/4_QC_scripts/diffusion_qcmetrics.ipynb
dwi.qc <- dwi.qc %>% rename(sub=subject_id) %>% rename(site=session_id) # format site variable
dwi.qc$site <- gsub("ses-", "", dwi.qc$site)
demographics <- merge(demographics, dwi.qc[,c("sub", "site")], by='sub') # add site info to demographics
dwi.qc <- dwi.qc[dwi.qc$sub %in% participants.final$sub,] # QC info for just the N = 1683 participants  
```

```{r}
acquisitionexclude <- dwi.qc %>% filter(raw_num_directions != 129) %>% select(sub) #participants to exclude from the final study sample for missing a diffusion MRI run (none)
participants.final <- participants.final[!participants.final$sub %in% acquisitionexclude$sub,] %>% as.data.frame() #remove 0 participants from the sample, remaining N = 1683
```

## Diffusion Quality Exclusion
```{r}
qualityexclude <- dwi.qc %>% filter(t1_neighbor_corr < 0.7) %>% select(sub) #participants to exclude from the final study sample based on processed diffusion MRI neighborhood correlation
participants.final <- participants.final[!participants.final$sub %in% qualityexclude$sub,] %>% as.data.frame() #remove 52 participants from the sample of 1683 due to diffusion data quality, remaining N = 1631
```

```{r}
# exclude based on expert rater score and CNN-i +q score from HBN-POD2 (CNN-i +q score is the definitive QC score, according to Richie-Halford paper)
pod2exclude <- participants.final %>% filter(expert_qc_score < 0.6 | dl_qc_score < 0.6) 
participants.final <- participants.final[!participants.final$sub %in% pod2exclude$sub,] %>% as.data.frame() # remove 489 participants from sample of 1631 due to failing expert rater, remaining N = 1142
```

## Diffusion Scan Head Motion Exclusion
```{r}
motionexclude <- dwi.qc %>% filter(mean_fd > 1) %>% select(sub) #participants to exclude from the final study sample based on high in-scanner head motion during the diffusion runs. (Note that 8 of these participants were already excluded in previous steps)
participants.final <- participants.final[!participants.final$sub %in% motionexclude$sub,] %>% as.data.frame()  #remove additional 40 participants from the sample of 1142 due to in-scanner head motion, remaining N = 1102
```

## Age Range Exclusion 
```{r}
participants.final <- participants.final[!participants.final$sub %in% demographics$sub[which(is.na(demographics$age))],] %>% as.data.frame()  #remove additional 1 participant from the sample of 1102 due to missing age data, remaining N = 1101
```

## Save Temporary Sample for PyAFQ: Subject List and Demographics
```{r}
# Make temp sample demographics dataframe
demographics.temp <- demographics[demographics$sub %in% participants.final$sub,] %>% select(sub, age, sex, race, site) # combine demographics data 
demographics.temp <- demographics.temp %>% mutate(sex = case_when(
  sex == "Male" ~ "M",
  sex == "Female" ~ "F"
))
# Make temp sample QC metrics dataframe 
dwi.qc.temp <- dwi.qc[dwi.qc$sub %in% participants.final$sub,] %>% select(sub, mean_fd, t1_neighbor_corr) 

sub_id <- participants.final$sub %>% as.data.frame() %>% setNames("sub_id")

write.table(sub_id, "/cbica/projects/luo_wm_dev/two_axes_manuscript/input/HBN/sample_selection_files/HBN_WMDev_TempSample_1101_age5to22.txt", col.names=T, row.names=F, quote = TRUE)
write.table(sub_id, "/cbica/projects/luo_wm_dev/two_axes_manuscript/input/HBN/subject_list/HBN_subject_list_babs.txt", col.names=T, row.names=F, quote = FALSE)
write.csv(demographics.temp, "/cbica/projects/luo_wm_dev/two_axes_manuscript/input/HBN/sample_selection_files/HBN_WMDev_TempSampleDemographics_N1101_age5to22.csv", quote = F, row.names = F)
write.csv(dwi.qc.temp, "/cbica/projects/luo_wm_dev/two_axes_manuscript/input/HBN/sample_selection_files/HBN_WMDev_TempSampleQCMetrics_N1101_age5to22.csv", quote = F, row.names = F)
```

