title: Two Axes of White Matter Development
author: "Audrey C. Luo"
theme: minima
#remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag

url: "https://pennlinc.github.io"
baseurl: "/luo_wm_dev"
header_pages:
  - about.md