title: Two Axes of White Matter Development
author:
  name: "Audrey C. Luo"
  email: "audrey.luo@pennmedicine.upenn.edu
  
theme: minima
#remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
url: "https://pennlinc.github.io"
baseurl: "/luo_wm_dev"
header_pages:
  - about.md